### ISSUE TITLE
Feature/Schedule page

### ISSUE THREAD

**Issue by fanesz** [Web-Programming/EthoxRiad#3]
- [x] Create pages/Schedule folder
- [x] Create index.tsx for layouting, and content.tsx for content
- [x] Focus on content page, because the layout will be implement after #1

**Comment by fanesz** [comment]
@Rendy752 jangan lupa pull origin main, ada merge #6 & #7

**Comment by Rendy752** [comment]
woke mo dicoba kalo dah kelar semua

**Comment by Rendy752** [comment]
https://github.com/Web-Programming/EthoxRiad/pull/8#issuecomment-2371226215
